STEP 1 : DATA LOADING, DATA CLEANING AND MERGING

import libraries

In [1]:
import pandas as pd
import numpy as np

STEP 2: Load All Datasets

In [2]:
transaction = pd.read_excel("Dataset/Transaction.xlsx")
user = pd.read_excel("Dataset/User.xlsx")
city = pd.read_excel("Dataset/City.xlsx")
country = pd.read_excel("Dataset/Country.xlsx")
region = pd.read_excel("Dataset/Region.xlsx")
continent = pd.read_excel("Dataset/Continent.xlsx")
atype = pd.read_excel("Dataset/Type.xlsx")
item = pd.read_excel("Dataset/Item.xlsx")

STEP 3: Quick Data Understanding

In [3]:
transaction.head()

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating
0,3,70456,2022,10,2,640,5
1,8,7567,2022,10,4,640,5
2,9,79069,2022,10,3,640,5
3,10,31019,2022,10,3,640,3
4,15,43611,2022,10,2,640,3

In [4]:
user.head(
    
)

   UserId  ContinentId  RegionId  CountryId  CityId
0      14            5        20        155   220.0
1      16            3        14        101  3098.0
2      20            4        15        109  4303.0
3      23            1         4         22   154.0
4      25            3        14        101  3098.0

In [5]:
city.head(
    
)

   CityId      CityName  CountryId
0       0             -          0
1       1        Douala          1
2       2  South Region          1
3       3     N'Djamena          2
4       4        Kigali          3

In [14]:
country.head()

   CountryId   Country  RegionId
0          0         -         0
1          1  Cameroon         1
2          2      Chad         1
3          3    Rwanda         1
4          4  Ethiopia         2

In [15]:
region.head()

            Region  RegionId  ContinentId
0                -         0            0
1   Central Africa         1            1
2      East Africa         2            1
3     North Africa         3            1
4  Southern Africa         4            1

In [16]:
continent.head()

   ContinentId            Continent
0            0                    -
1            1               Africa
2            2              America
3            3                 Asia
4            4  Australia & Oceania

In [15]:
atype.head()

   AttractionTypeId         AttractionType
0                 2          Ancient Ruins
1                10                Ballets
2                13                Beaches
3                19        Caverns & Caves
4                34  Flea & Street Markets

In [18]:
item.head()

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
0,369,1,13,Kuta Beach - Bali,Kuta
1,481,1,13,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia"
2,640,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia"
3,650,1,13,Sanur Beach,Sanur
4,673,1,13,Seminyak Beach,Seminyak

1. Shape is count rows and columns

In [16]:
transaction.shape
user.shape
city.shape
continent.shape
country.shape
item.shape
region.shape
atype.shape

(17, 2)

2.Handle Missing Values

In [17]:
transaction.isnull().sum()

TransactionId    0
UserId           0
VisitYear        0
VisitMonth       0
VisitMode        0
AttractionId     0
Rating           0
dtype: int64

In [22]:
city.isnull().sum(
    
)

CityId       0
CityName     1
CountryId    0
dtype: int64

In [23]:
continent.isnull().sum()

ContinentId    0
Continent      0
dtype: int64

In [24]:
country.isnull().sum()

CountryId    0
Country      0
RegionId     0
dtype: int64

In [25]:
item.isnull().sum()

AttractionId         0
AttractionCityId     0
AttractionTypeId     0
Attraction           0
AttractionAddress    0
dtype: int64

In [26]:
user.isnull().sum()

UserId         0
ContinentId    0
RegionId       0
CountryId      0
CityId         4
dtype: int64

Fix Rating Column

In [29]:
transaction["Rating"] = pd.to_numeric(transaction["Rating"], errors="coerce")
transaction = transaction.dropna(subset=["Rating"])

MERGE LOCATION DATA
# Merge User + City

In [6]:
user_city = user.merge(city, on="CityId", how="left")

# Merge Country, Region, Continent

In [7]:
user_location = (
    user_city
    .merge(country, left_on="CountryId_x", right_on="CountryId", how="left")
    .merge(region, left_on="RegionId_y", right_on="RegionId", how="left")
    .merge(continent, left_on="ContinentId_y", right_on="ContinentId", how="left")
)

# MERGE ATTRACTION DATA

In [8]:
item_full = item.merge(atype, on="AttractionTypeId", how="left")

# FINAL MASTER MERGE

In [9]:
final_df = (
    transaction
    .merge(user_location, on="UserId", how="left")
    .merge(item_full, on="AttractionId", how="left")
)

# Remove Duplicates

In [10]:
final_df.drop_duplicates(inplace=True)

# Final Check

In [11]:
final_df.info()
final_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52930 entries, 0 to 52929
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TransactionId      52930 non-null  int64
 1   UserId             52930 non-null  int64
 2   VisitYear          52930 non-null  int64
 3   VisitMonth         52930 non-null  int64
 4   VisitMode          52930 non-null  int64
 5   AttractionId       52930 non-null  int64
 6   Rating             52930 non-null  int64
 7   ContinentId_x      52930 non-null  int64
 8   RegionId_x         52930 non-null  int64
 9   CountryId_x        52930 non-null  int64
 10  CityId             52922 non-null  float64
 11  CityName           52922 non-null  object
 12  CountryId_y        52922 non-null  float64
 13  CountryId          52930 non-null  int64
 14  Country            52930 non-null  object
 15  RegionId_y         52930 non-null  int64
 16  Region             52930 non-null  object
 17  RegionId           52930 non-null  int64
 18  ContinentId_y      52930 non-null  int64
 19  ContinentId        52930 non-null  int64
 20  Continent          52930 non-null  object
 21  AttractionCityId   52930 non-null  int64
 22  AttractionTypeId   52930 non-null  int64
 23  Attraction         52930 non-null  object
 24  AttractionAddress  52930 non-null  object
 25  AttractionType     52930 non-null  object
dtypes: float64(2), int64(17), object(7)
memory usage: 10.5+ MB

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating,ContinentId_x,RegionId_x,CountryId_x,...,Region,RegionId,ContinentId_y,ContinentId,Continent,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress,AttractionType
0,3,70456,2022,10,2,640,5,5,21,163,...,Western Europe,21,5,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas
1,8,7567,2022,10,4,640,5,2,8,48,...,Northern America,8,2,2,America,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas
2,9,79069,2022,10,3,640,5,2,9,54,...,South America,9,2,2,America,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas
3,10,31019,2022,10,3,640,3,5,17,135,...,Central Europe,17,5,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas
4,15,43611,2022,10,2,640,3,5,21,163,...,Western Europe,21,5,5,Europe,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia",Nature & Wildlife Areas

# Save Cleaned Data

In [36]:
final_df.to_csv("cleaned_tourism_data.csv", index=False)